// This file will be auto-generated by Supabase CLI
// Run: npx supabase gen types typescript --project-id YOUR_PROJECT_ID > lib/types/database.ts
// For now, we define placeholder types

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          name: string;
          role: "owner" | "partner";
          created_at: string;
        };
        Insert: {
          id: string;
          name: string;
          role?: "owner" | "partner";
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          role?: "owner" | "partner";
          created_at?: string;
        };
      };
      filaments: {
        Row: {
          id: string;
          type: string;
          brand: string | null;
          color: string;
          color_hex: string | null;
          weight_remaining_g: number;
          initial_weight_g: number;
          purchase_date: string | null;
          cost: number | null;
          supplier: string | null;
          storage_location: string | null;
          low_stock_threshold_g: number;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          type: string;
          brand?: string | null;
          color: string;
          color_hex?: string | null;
          weight_remaining_g?: number;
          initial_weight_g?: number;
          purchase_date?: string | null;
          cost?: number | null;
          supplier?: string | null;
          storage_location?: string | null;
          low_stock_threshold_g?: number;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          type?: string;
          brand?: string | null;
          color?: string;
          color_hex?: string | null;
          weight_remaining_g?: number;
          initial_weight_g?: number;
          purchase_date?: string | null;
          cost?: number | null;
          supplier?: string | null;
          storage_location?: string | null;
          low_stock_threshold_g?: number;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      printers: {
        Row: {
          id: string;
          name: string;
          model: string | null;
          serial_number: string | null;
          purchase_date: string | null;
          status: "idle" | "printing" | "maintenance" | "offline";
          usage_hours: number;
          initial_hours: number;
          power_watts: number;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          model?: string | null;
          serial_number?: string | null;
          purchase_date?: string | null;
          status?: "idle" | "printing" | "maintenance" | "offline";
          usage_hours?: number;
          initial_hours?: number;
          power_watts?: number;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          model?: string | null;
          serial_number?: string | null;
          purchase_date?: string | null;
          status?: "idle" | "printing" | "maintenance" | "offline";
          usage_hours?: number;
          initial_hours?: number;
          power_watts?: number;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      customers: {
        Row: {
          id: string;
          name: string;
          email: string | null;
          phone: string | null;
          address: string | null;
          preferred_contact: string;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          email?: string | null;
          phone?: string | null;
          address?: string | null;
          preferred_contact?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          email?: string | null;
          phone?: string | null;
          address?: string | null;
          preferred_contact?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      orders: {
        Row: {
          id: string;
          order_number: string;
          customer_id: string | null;
          assigned_to: string | null;
          printer_id: string | null;
          status:
            | "pending"
            | "in_queue"
            | "printing"
            | "post_processing"
            | "ready"
            | "delivered"
            | "cancelled";
          total_cost: number | null;
          notes: string | null;
          due_date: string | null;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          order_number: string;
          customer_id?: string | null;
          assigned_to?: string | null;
          printer_id?: string | null;
          status?:
            | "pending"
            | "in_queue"
            | "printing"
            | "post_processing"
            | "ready"
            | "delivered"
            | "cancelled";
          total_cost?: number | null;
          notes?: string | null;
          due_date?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          order_number?: string;
          customer_id?: string | null;
          assigned_to?: string | null;
          printer_id?: string | null;
          status?:
            | "pending"
            | "in_queue"
            | "printing"
            | "post_processing"
            | "ready"
            | "delivered"
            | "cancelled";
          total_cost?: number | null;
          notes?: string | null;
          due_date?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {};
    Functions: {};
    Enums: {};
  };
}
